export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const ADD_NEW_PROJECT = "ADD_NEW_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const GET_ALL_PROJECTS = "GET_ALL_PROJECTS";
export const GET_USER_PROJECT = "GET_USER_PROJECT";
